# Generated by Django 6.0.1 on 2026-01-29 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TabletopSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the system.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the tabletop system.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A description of the system.')),
            ],
            options={
                'verbose_name': 'Tabletop System',
                'verbose_name_plural': 'Tabletop Systems',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the campaign.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the campaign.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A description of the campaign and its adventures.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the campaign was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the campaign was last updated.')),
                ('dungeon_master', models.ForeignKey(help_text='The Game Master/Dungeon Master of the campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='managed_campaigns', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(blank=True, help_text='The players who are members of this campaign.', related_name='joined_campaigns', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(blank=True, help_text='The tabletop system used for this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='dunbud.tabletopsystem')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
