# Generated by Django 6.0.1 on 2026-01-30 19:22
import json
import os

from django.db import migrations


def load_systems_from_file(apps, schema_editor):
    TabletopSystem = apps.get_model('dunbud', 'TabletopSystem')

    # 1. Construct the path to the JSON file
    # __file__ is the path to *this* python file
    # We go up one level (..) to the app dir, then into 'data'
    file_path = os.path.join(os.path.dirname(__file__), '../data/TabletopSystems.json')

    # 2. Open and read the JSON
    with open(file_path, 'r') as f:
        data = json.load(f)

    # 3. Create objects
    # Note: We use ignore_conflicts=True so re-running doesn't crash on duplicates
    systems_to_create = [TabletopSystem(**item) for item in data]

    # 4. Load into database
    TabletopSystem.objects.bulk_create(systems_to_create, ignore_conflicts=True)

class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_systems_from_file),
    ]
