# Generated by Django 6.0.1 on 2026-01-30 19:22

from django.db import migrations


def create_ttrpgs(apps, schema_editor):
    # We get the model from the versioned app registry
    TabletopSystem = apps.get_model('dunbud', 'TabletopSystem')

    defaults = [
        # --- DUNGEONS & DRAGONS FAMILY ---
        {
            "name": "Dungeons & Dragons (2024 Revised 5e)",
            "short_name": "D&D 2024",
            "description": "The modern refined standard of 5e, streamlining class features and integrating digital-first design principles."
        },
        {
            "name": "Dungeons & Dragons (5e 2014)",
            "short_name": "D&D 5e (Classic)",
            "description": "The blockbuster edition that brought TTRPGs to the mainstream, known for the Advantage/Disadvantage system and accessibility."
        },
        {
            "name": "Dungeons & Dragons (4e)",
            "short_name": "D&D 4e",
            "description": "A highly tactical, grid-focused edition that treated every class with a 'power' system similar to MMO cooldowns."
        },
        {
            "name": "Dungeons & Dragons (v3.5)",
            "short_name": "D&D 3.5",
            "description": "The 'high crunch' era of d20 gaming, famous for endless prestige classes, feats, and the Open Game License explosion."
        },
        {
            "name": "Advanced Dungeons & Dragons (2e)",
            "short_name": "AD&D 2e",
            "description": "The 90s era of legendary campaign settings like Planescape and Dark Sun; it cleaned up 1e and introduced 'kits'."
        },
        {
            "name": "Advanced Dungeons & Dragons (1e)",
            "short_name": "AD&D 1e",
            "description": "Gary Gygax’s definitive unified ruleset; the foundation of the 'Gygaxian' dungeon crawl with high lethality."
        },
        {
            "name": "Dungeons & Dragons (Basic/Expert/BECMI)",
            "short_name": "D&D B/X",
            "description": "The 'Classic' branch of D&D where Race was your Class (e.g., you played an 'Elf') and rules were simpler than AD&D."
        },
        {
            "name": "Original Dungeons & Dragons (1974)",
            "short_name": "OD&D",
            "description": "The three original brown booklets that started the hobby, requiring the 'Chainmail' wargame for combat rules."
        },

        # --- PATHFINDER FAMILY ---
        {
            "name": "Pathfinder (2e Remaster)",
            "short_name": "PF2e (Remaster)",
            "description": "The 2024/2025 update that removed D&D-specific terminology and Alignment to become a fully independent system."
        },
        {
            "name": "Pathfinder (2e)",
            "short_name": "PF2e",
            "description": "The 2019 launch of the three-action economy, focusing on tight math, balanced encounters, and deep customization."
        },
        {
            "name": "Pathfinder (1e)",
            "short_name": "PF1e",
            "description": "Known as 'D&D 3.75,' this system took the 3.5e rules and expanded them into a massive, decade-long library of options."
        },
        {
            "name": "Call of Cthulhu (7e)",
            "short_name": "CoC 7e",
            "description": "A d100-based horror system where players investigate cosmic mysteries while managing their character's dwindling sanity."
        },
        {
            "name": "Draw Steel (1e)",
            "short_name": "Draw Steel",
            "description": "MCDM’s cinematic tactical RPG designed to make players feel like legendary heroes with high-impact, resource-driven combat."
        },
        {
            "name": "Daggerheart (1e)",
            "short_name": "Daggerheart",
            "description": "Darrington Press’s narrative-forward system using a 2d12 'Duality' mechanic to balance story outcomes between Hope and Fear."
        },
        {
            "name": "Cosmere RPG (1e)",
            "short_name": "Cosmere RPG",
            "description": "A d20 system covering Brandon Sanderson’s universe, featuring specialized mechanics for Stormlight hexcrawl and Mistborn heists."
        },
        {
            "name": "Cyberpunk RED (Current Edition)",
            "short_name": "Cyberpunk RED",
            "description": "A gritty, high-stakes game of survival in a neon-drenched future where 'style over substance' and lethal combat are law."
        },
        {
            "name": "Vampire: The Masquerade (5e)",
            "short_name": "VtM 5e",
            "description": "A game of personal and political horror where players struggle with their inner beast and the complex social web of the Kindred."
        },
        {
            "name": "Ars Magica (Definitive Edition)",
            "short_name": "ArM (Definitive)",
            "description": "The gold standard for magic systems, focusing on a covenant of wizards in Mythic Europe using a highly flexible 'verb-noun' spell engine."
        },
        {
            "name": "Shadowdark (1e)",
            "short_name": "Shadowdark",
            "description": "A minimalist 'Old School' fantasy game that prioritizes fast-paced dungeon crawling and real-time torch management."
        },
        {
            "name": "Warhammer Fantasy Roleplay (5e)",
            "short_name": "WFRP 5e",
            "description": "A grim and perilous system where players take on mundane professions to survive a world of chaos, corruption, and dark humor."
        },
        {
            "name": "Starfinder (2e)",
            "short_name": "Starfinder 2e",
            "description": "A science-fantasy overhaul built on the Pathfinder 2e engine, bringing high-tech gear and starship combat into a cohesive tactical framework."
        },
        {
            "name": "Mothership (1e)",
            "short_name": "Mothership 1e",
            "description": "A d100 sci-fi horror RPG designed for high-tension 'oneshots' or campaigns where survival against alien threats is never guaranteed."
        },
        {
            "name": "Old School Essentials (Redux)",
            "short_name": "OSE (Redux)",
            "description": "The premier B/X D&D clone, celebrated for its perfect layout and faithful recreation of 1980s-era fantasy roleplaying."
        },
        {
            "name": "The One Ring (2e)",
            "short_name": "TOR 2e",
            "description": "An evocative adaptation of Tolkien's Middle-earth that focuses on the themes of travel, shadow, and the fellowship of heroes."
        },
        {
            "name": "Blades in the Dark (1e)",
            "short_name": "Blades",
            "description": "The original 'Forged in the Dark' system where players play a crew of scoundrels performing heists in a haunted Victorian-style city."
        },
        {
            "name": "Dragonbane (1e)",
            "short_name": "Dragonbane",
            "description": "A Swedish d20-based fantasy RPG known for its 'mirth and mayhem' approach and fast, accessible ruleset."
        },
        {
            "name": "13th Age (2e)",
            "short_name": "13th Age 2e",
            "description": "A high-action fantasy game that blends the best of d20 tactical combat with modern narrative mechanics like 'One Unique Things'."
        },
        {
            "name": "Alien: The Roleplaying Game (2e)",
            "short_name": "Alien RPG 2e",
            "description": "A cinematic horror game that uses a unique Stress mechanic to simulate the mounting panic of facing the perfect organism."
        },
        {
            "name": "Delta Green (Current Edition)",
            "short_name": "Delta Green",
            "description": "A modern-day horror system where agents work for a secret government agency to contain supernatural threats at the cost of their personal lives."
        }
    ]

    # Bulk create is faster than looping
    TabletopSystem.objects.bulk_create([TabletopSystem(**default) for default in defaults])

class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_ttrpgs),
    ]
