# Generated by Django 6.0.1 on 2026-02-02 17:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0002_auto_20260130_1922'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the character.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the character.', max_length=255)),
                ('race', models.CharField(blank=True, help_text='The race/ancestry of the character.', max_length=100)),
                ('character_class', models.CharField(blank=True, help_text='The class/job of the character.', max_length=100, verbose_name='Class')),
                ('level', models.PositiveIntegerField(default=1, help_text='The level of the character.')),
                ('bio', models.TextField(blank=True, help_text='Character biography and description.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the character was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the character was last updated.')),
                ('campaign', models.ForeignKey(blank=True, help_text='The campaign this character belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='dunbud.campaign')),
                ('user', models.ForeignKey(help_text='The user who owns this character.', on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PlayerCharacter',
                'verbose_name_plural': 'PlayerCharacters',
                'ordering': ['name'],
            },
        ),
    ]
