# Generated by Django 6.0.1 on 2026-01-29 21:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0002_alter_campaign_dungeon_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyFeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(help_text='The text content of the feed item.', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this feed item was created.')),
                ('campaign', models.ForeignKey(help_text='The campaign this feed item belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='dunbud.campaign')),
            ],
            options={
                'verbose_name': 'Party Feed Item',
                'verbose_name_plural': 'Party Feed Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
