# Generated by Django 6.0.1 on 2026-02-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0003_playercharacter'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacter',
            name='character_sheet_link',
            field=models.URLField(blank=True, help_text="A link to the character's sheet."),
        ),
    ]
