# Generated by Django 6.0.1 on 2026-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0005_campaigninvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_players',
            field=models.PositiveIntegerField(default=6, help_text='The maximum number of players allowed in the campaign.'),
        ),
    ]
