# Generated by Django 6.0.2 on 2026-02-04 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0006_campaign_max_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpfulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_links', to='dunbud.campaign')),
            ],
        ),
    ]
