# Generated by Django 6.0.2 on 2026-02-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0007_helpfullink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyfeeditem',
            name='message',
            field=models.TextField(help_text='The text content of the feed item. Supports Markdown.'),
        ),
    ]
