# Generated by Django 6.0.2 on 2026-02-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0008_alter_partyfeeditem_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyfeeditem',
            name='category',
            field=models.CharField(choices=[('membership', 'Membership'), ('announcements', 'Announcements'), ('data_updates', 'Data Updates'), ('journal', 'Journal')], default='announcements', help_text='The category of this feed item.', max_length=20),
        ),
    ]
