# Generated by Django 6.0.2 on 2026-02-10 21:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0009_partyfeeditem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_date', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('168.00'))])),
                ('session_number', models.PositiveIntegerField(default=1, help_text='The sequential number of the session within the campaign.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_sessions', to=settings.AUTH_USER_MODEL)),
                ('busy_users', models.ManyToManyField(blank=True, related_name='busy_sessions', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dunbud.campaign')),
                ('proposer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['proposed_date'],
            },
        ),
    ]
