# Generated by Django 6.0.2 on 2026-02-10 20:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0010_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('168.00'))]),
        ),
    ]
