# Generated by Django 6.0.2 on 2026-02-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0011_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
