# Generated by Django 6.0.2 on 2026-02-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0012_session_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, help_text='The URL-friendly identifier for the campaign.', max_length=255, unique=True),
        ),
    ]
