# Generated by Django 6.0.2 on 2026-02-12 19:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0013_campaign_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier for the journal entry.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The headline or title of the entry.', max_length=255)),
                ('content', models.TextField(help_text='The main body of the journal entry.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the entry was last updated.')),
                ('character', models.ForeignKey(help_text='The character who wrote this entry.', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='dunbud.playercharacter')),
                ('session', models.ForeignKey(blank=True, help_text='The session this entry is about (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='dunbud.session')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
