# Generated by Django 6.0.2 on 2026-02-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dunbud', '0014_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='recap',
            field=models.TextField(blank=True, help_text='Post-session recap and summary.'),
        ),
        migrations.AlterField(
            model_name='partyfeeditem',
            name='category',
            field=models.CharField(choices=[('membership', 'Membership'), ('announcements', 'Announcements'), ('data_updates', 'Data Updates'), ('journal', 'Journal'), ('recap', 'Session Recap')], default='announcements', help_text='The category of this feed item.', max_length=20),
        ),
    ]
