# Generated by Django 6.0.1 on 2026-02-02 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the announcement.', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of the title.', unique=True)),
                ('content', models.TextField(help_text='The body content of the announcement.')),
                ('is_published', models.BooleanField(default=False, help_text='Designates whether this post is visible to the public.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the post was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when the post was last updated.')),
                ('author', models.ForeignKey(help_text='The admin who created the post.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-created_at'],
            },
        ),
    ]
